### PR TITLE
enable numaclt,python-thrift package install test

### LINKED ISSUE #4: add some serverspec tests
http://serverspec.org/

### PR DESCRIPTION
**Pull request by mburns**
fixes #4 

Enable serverspec tests

### CODE REVIEW

**Comment by drenalin23** [comment]
+1

**Comment by mburns** [comment]
```
           ================================================================================
           Error executing action `install` on resource 'apt_package[python-thrift]'
           ================================================================================
           
           Chef::Exceptions::Package
           -------------------------
           No candidate version available for python-thrift
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/cassandra/recipes/default.rb
           
            20: package 'python-thrift' do
        21:   ignore_failure true
            22: end
            23: 
```

- [ ] remove `ignore_failure true`
- [ ] fix package name(?)

**Comment by drenalin23** [comment]
That package should exist for trusty - http://packages.ubuntu.com/trusty/python-thrift

**Comment by drenalin23** [comment]
Interestingly when I run kitchen test - python-thrift works, but numactl fails.  =)

-----> serverspec installed (version 2.36.0)
       /opt/chef/embedded/bin/ruby -I/tmp/verifier/suites/serverspec -I/tmp/verifier/gems/gems/rspec-support-3.5.0/lib:/tmp/verifier/gems/gems/rspec-core-3.5.1/lib /opt/chef/embedded/bin/rspec --pattern /tmp/verifier/suites/serverspec/\*\*/\*_spec.rb --color --format documentation --default-path /tmp/verifier/suites/serverspec
       
       Package "numactl"
         should be installed (FAILED - 1)
       
       Package "python-thrift"
         should be installed
       
       Failures:
       
         1) Package "numactl" should be installed
            Failure/Error: it { should be_installed }
              expected Package "numactl" to be installed
              /bin/sh -c dpkg-query\ -f\ \'\$\{Status\}\'\ -W\ numactl\ \|\ grep\ -E\ \'\^\(install\|hold\)\ ok\ installed\$\'
              
            # /tmp/verifier/suites/serverspec/cassandra_spec.rb:8:in `block (2 levels) in <top (required)>'
       
       Finished in 0.11022 seconds (files took 0.30956 seconds to load)
       2 examples, 1 failure
       
       Failed examples:
       
       rspec /tmp/verifier/suites/serverspec/cassandra_spec.rb:8 # Package "numactl" should be installed

**Pull request merged**
